require("dotenv").config()
const express=require("express")
const app=express()
const routes=require("./routes")
const errorHandler=require("./middlewares/errorHandler")
app.use(express.json())
app.use("/api/v1",routes)
app.use((req,res)=>res.status(404).json({error:"Not found"}))
app.use(errorHandler)
const port=process.env.PORT||4000
app.listen(port,()=>{console.log(`Server running on ${port}`)})
